/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "avatar": string|undefined
  "avatarContainer": string|undefined
  "avatarRight": string|undefined
  "equalSign": string|undefined
  "routeInfoContainer": string|undefined
  "swapContainer": string|undefined
  "swapDetailsContainer": string|undefined
  "swapPriceTag": string|undefined
  "swapTagContainer": string|undefined
  "tokenContainer": string|undefined
  "tokenRow": string|undefined
  "tokenRowHeader": string|undefined
}
