/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export interface CssIdentifiersMap {
	avatarContainer: string | undefined
	equalSign: string | undefined
	inputFocused: string | undefined
	invisible: string | undefined
	roueteCardsContainer: string | undefined
	routeInfoContainer: string | undefined
	swapButton: string | undefined
	swapContainer: string | undefined
	swapDetailsContainer: string | undefined
	swapPriceTag: string | undefined
	swapTagContainer: string | undefined
	tokenContainer: string | undefined
	tokenRow: string | undefined
	tokenRowHeader: string | undefined
}
