/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
	inline: string | undefined
	inputIcon: string | undefined
	inputWrapper: string | undefined
}
