/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "button": string|undefined
  "isLoading": string|undefined
  "lg": string|undefined
  "md": string|undefined
  "pressable-down": string|undefined
  "primary": string|undefined
  "secondary": string|undefined
  "sm": string|undefined
  "xl": string|undefined
}
