/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export interface CssIdentifiersMap {
	black: string | undefined
	button: string | undefined
	filled: string | undefined
	isDisabled: string | undefined
	isLoading: string | undefined
	lg: string | undefined
	md: string | undefined
	'pressable-down': string | undefined
	primary: string | undefined
	secondary: string | undefined
	sm: string | undefined
	'sq-lg': string | undefined
	'sq-md': string | undefined
	'sq-sm': string | undefined
	'sq-xs': string | undefined
	subtle: string | undefined
	xl: string | undefined
	xs: string | undefined
}
