/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  'cellComponentContainer': string | undefined
  'container': string | undefined
  'truncate': string | undefined
}
