/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export interface CssIdentifiersMap {
	container: string | undefined
	skeletonCell: string | undefined
	skeletonColumns: string | undefined
	skeletonHeader: string | undefined
	skeletonHeaderCell: string | undefined
	skeletonTable: string | undefined
}
