/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export interface CssIdentifiersMap {
	avatar: string | undefined
	container: string | undefined
	lg: string | undefined
	md: string | undefined
	sm: string | undefined
	xs: string | undefined
}
