export const config = {
	baseURL: process.env.CONCERO_API_URL as string,
	headers: { 'Content-Type': 'application/json' },
	CRYPTOPANIC_API_KEY: process.env.CRYPTOPANIC_API_KEY as string,
	LIFI_INTEGRATOR: process.env.LIFI_INTEGRATOR as string,
	LIFI_FEES: process.env.LIFI_FEES as string,
	RANGO_API_KEY: process.env.RANGO_API_KEY as string,
	ENSO_API_KEY: process.env.ENSO_API_KEY as string,
	POSTHOG_API_KEY: process.env.POSTHOG_API_KEY as string,
	POSTHOG_HOST: process.env.POSTHOG_HOST as string,
	NULL_ADDRESS: '0x0000000000000000000000000000000000000000',
	NULL_E_ADDRESS: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
	WEB3_MODAL_PROJECT_ID: process.env.WEB3_MODAL_PROJECT_ID as string,
	OKX_API_KEY: <string>process.env.OKX_API_KEY,
	OKX_SECRET_KEY: <string>process.env.OKX_SECRET_KEY,
	OKX_PASSPHRASE: <string>process.env.OKX_PASSPHRASE,
	OKX_PROJECT_ID: <string>process.env.OKX_PROJECT_ID,
}
