export const routes = {
	home: '/',
	root: '/',
	pool: '/pool',
	rewards: '/rewards',
	swap: '/swap',
	auth: '/auth',
	login: '/login',
	signup: '/signup',
	profile: '/profile',
	earn: '/earn',
	portfolio: '/portfolio',
	notFound: '/404',
	resetPassword: '/reset-password',
}
