/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export interface CssIdentifiersMap {
	body1: string | undefined
	dark: string | undefined
	light: string | undefined
	root: string | undefined
	tradingview_widget_wrapper: string | undefined
}
