/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "bottomRow": string|undefined
  "container": string|undefined
  "lg": string|undefined
  "md": string|undefined
  "secondary": string|undefined
  "sm": string|undefined
  "topRow": string|undefined
}
