/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export interface CssIdentifiersMap {
	additionalInfoTag: string | undefined
	advantageTagColor: string | undefined
	avatarContainer: string | undefined
	bestButton: string | undefined
	bestCard: string | undefined
	bestTag: string | undefined
	bestText: string | undefined
	bodyColor: string | undefined
	cardHeader: string | undefined
	cardHeaderLeftSide: string | undefined
	chainAvatar: string | undefined
	container: string | undefined
	endPointContainer: string | undefined
	fullWidth: string | undefined
	infoTagsContainer: string | undefined
	routeStep: string | undefined
	routeStepContainer: string | undefined
	showAllTag: string | undefined
	stepInfoContainer: string | undefined
	stepsContainer: string | undefined
	subtitle: string | undefined
	tagStyle: string | undefined
	textSubtitle: string | undefined
}
