/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "additionalInfoTag": string|undefined
  "avatarContainer": string|undefined
  "cardHeader": string|undefined
  "cardHeaderLeftSide": string|undefined
  "chainAvatar": string|undefined
  "container": string|undefined
  "endPointContainer": string|undefined
  "fullWidth": string|undefined
  "routeStep": string|undefined
  "routeStepContainer": string|undefined
  "showAllTag": string|undefined
  "stepInfoContainer": string|undefined
  "stepsContainer": string|undefined
  "subtitle": string|undefined
  "tagStyle": string|undefined
  "textSubtitle": string|undefined
}
