export const lifiChains = [
    {
        key: 'eth',
        chainType: 'EVM',
        name: 'Ethereum',
        symbol: 'ETH',
        id: 1,
        mainnet: true,
        logoURI: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/ethereum.svg',
        tokenlistUrl: 'https://gateway.ipfs.io/ipns/tokens.uniswap.org',
        multicallAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
        metamask: {
            chainId: '0x1',
            blockExplorerUrls: ['https://etherscan.io/'],
            chainName: 'Ethereum Mainnet',
            nativeCurrency: {
                name: 'ETH',
                symbol: 'ETH',
                decimals: 18,
            },
            rpcUrls: ['https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161'],
        },
        nativeToken: {
            address: '0x0000000000000000000000000000000000000000',
            chainId: 1,
            symbol: 'ETH',
            decimals: 18,
            name: 'ETH',
            priceUSD: '1931.14',
            logoURI: 'https://static.debank.com/image/token/logo_url/eth/935ae4e4d1d12d59a99717a24f2540b5.png',
            coinKey: 'ETH',
        },
    },
    {
        key: 'pol',
        chainType: 'EVM',
        name: 'Matic',
        symbol: 'MATIC',
        id: 137,
        mainnet: true,
        logoURI: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/polygon.svg',
        tokenlistUrl: 'https://unpkg.com/quickswap-default-token-list@1.0.71/build/quickswap-default.tokenlist.json',
        faucetUrls: ['https://stakely.io/faucet/polygon-matic'],
        multicallAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
        metamask: {
            chainId: '0x89',
            blockExplorerUrls: ['https://polygonscan.com/', 'https://explorer-mainnet.maticvigil.com/'],
            chainName: 'Matic(Polygon) Mainnet',
            nativeCurrency: {
                name: 'MATIC',
                symbol: 'MATIC',
                decimals: 18,
            },
            rpcUrls: ['https://polygon-rpc.com/', 'https://rpc-mainnet.maticvigil.com/'],
        },
        nativeToken: {
            address: '0x0000000000000000000000000000000000000000',
            chainId: 137,
            symbol: 'MATIC',
            decimals: 18,
            name: 'MATIC',
            priceUSD: '0.783213',
            logoURI: 'https://static.debank.com/image/matic_token/logo_url/matic/6f5a6b6f0732a7a235131bd7804d357c.png',
            coinKey: 'MATIC',
        },
    },
    {
        key: 'bsc',
        chainType: 'EVM',
        name: 'BSC',
        symbol: 'BNB',
        id: 56,
        mainnet: true,
        logoURI: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/bsc.svg',
        tokenlistUrl: 'https://tokens.pancakeswap.finance/pancakeswap-extended.json',
        faucetUrls: ['https://stakely.io/faucet/bsc-chain-bnb'],
        multicallAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
        metamask: {
            chainId: '0x38',
            blockExplorerUrls: ['https://bscscan.com/'],
            chainName: 'Binance Smart Chain Mainnet',
            nativeCurrency: {
                name: 'BNB',
                symbol: 'BNB',
                decimals: 18,
            },
            rpcUrls: [
                'https://bsc-dataseed.binance.org/',
                'https://bsc-dataseed1.defibit.io/',
                'https://bsc-dataseed1.ninicoin.io/',
            ],
        },
        nativeToken: {
            address: '0x0000000000000000000000000000000000000000',
            chainId: 56,
            symbol: 'BNB',
            decimals: 18,
            name: 'BNB',
            priceUSD: '243.5',
            logoURI: 'https://static.debank.com/image/coin/logo_url/bnb/9784283a36f23a58982fc964574ea530.png',
            coinKey: 'BNB',
        },
    },
    {
        key: 'dai',
        chainType: 'EVM',
        name: 'Gnosis',
        symbol: 'DAI',
        id: 100,
        mainnet: true,
        logoURI: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/gnosis.svg',
        tokenlistUrl: 'https://tokens.honeyswap.org/',
        faucetUrls: ['https://stakely.io/faucet/xdai-chain'],
        multicallAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
        metamask: {
            chainId: '0x64',
            blockExplorerUrls: ['https://blockscout.com/xdai/mainnet/'],
            chainName: 'Gnosis Chain',
            nativeCurrency: {
                name: 'xDai',
                symbol: 'xDai',
                decimals: 18,
            },
            rpcUrls: ['https://rpc.gnosischain.com/', 'https://rpc.ankr.com/gnosis', 'https://xdai-rpc.gateway.pokt.network'],
        },
        nativeToken: {
            address: '0x0000000000000000000000000000000000000000',
            chainId: 100,
            symbol: 'xDAI',
            decimals: 18,
            name: 'xDAI Native Token',
            priceUSD: '1',
            logoURI: 'https://static.debank.com/image/xdai_token/logo_url/xdai/1207e67652b691ef3bfe04f89f4b5362.png',
            coinKey: 'DAI',
        },
    },
    {
        key: 'ftm',
        chainType: 'EVM',
        name: 'Fantom',
        symbol: 'FTM',
        id: 250,
        mainnet: true,
        logoURI: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/fantom.svg',
        tokenlistUrl: 'https://raw.githubusercontent.com/SpookySwap/spooky-info/master/src/constants/token/spookyswap.json',
        faucetUrls: [
            'https://stakely.io/faucet/fantom-blockchain-ftm',
            'https://docs.spookyswap.finance/getting-started/how-to-get-fantom-gas',
        ],
        multicallAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
        metamask: {
            chainId: '0xfa',
            blockExplorerUrls: ['https://ftmscan.com/'],
            chainName: 'Fantom Opera',
            nativeCurrency: {
                name: 'FTM',
                symbol: 'FTM',
                decimals: 18,
            },
            rpcUrls: ['https://rpc.ftm.tools/', 'https://rpcapi.fantom.network'],
        },
        nativeToken: {
            address: '0x0000000000000000000000000000000000000000',
            chainId: 250,
            symbol: 'FTM',
            decimals: 18,
            name: 'FTM',
            priceUSD: '0.2685',
            logoURI: 'https://static.debank.com/image/ftm_token/logo_url/ftm/33fdb9c5067e94f3a1b9e78f6fa86984.png',
            coinKey: 'FTM',
        },
    },
    {
        key: 'okt',
        chainType: 'EVM',
        name: 'OKXChain',
        symbol: 'OKT',
        id: 66,
        mainnet: true,
        logoURI: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/okx.svg',
        tokenlistUrl: 'https://raw.githubusercontent.com/sushiswap/default-token-list/master/tokens/okex.json',
        multicallAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
        metamask: {
            chainId: '0x42',
            blockExplorerUrls: ['https://www.oklink.com/en/okc/'],
            chainName: 'OKXChain Mainnet',
            nativeCurrency: {
                name: 'OKT',
                symbol: 'OKT',
                decimals: 18,
            },
            rpcUrls: ['https://exchainrpc.okex.org'],
        },
        nativeToken: {
            address: '0x0000000000000000000000000000000000000000',
            chainId: 66,
            symbol: 'OKT',
            decimals: 18,
            name: 'OKT',
            priceUSD: '15.09',
            logoURI:
                'https://static.debank.com/image/okt_token/logo_url/0x8f8526dbfd6e38e3d8307702ca8469bae6c56c15/54a64333ea780b76b96435d66ab41146.png',
            coinKey: 'OKT',
        },
    },
    {
        key: 'ava',
        chainType: 'EVM',
        name: 'Avalanche',
        symbol: 'AVAX',
        id: 43114,
        mainnet: true,
        logoURI: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/avalanche.svg',
        tokenlistUrl: 'https://raw.githubusercontent.com/sushiswap/default-token-list/master/tokens/avalanche.json',
        multicallAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
        metamask: {
            chainId: '0xa86a',
            blockExplorerUrls: ['https://cchain.explorer.avax.network/'],
            chainName: 'Avalanche Mainnet',
            nativeCurrency: {
                name: 'AVAX',
                symbol: 'AVAX',
                decimals: 18,
            },
            rpcUrls: ['https://api.avax.network/ext/bc/C/rpc'],
        },
        nativeToken: {
            address: '0x0000000000000000000000000000000000000000',
            chainId: 43114,
            symbol: 'AVAX',
            decimals: 18,
            name: 'AVAX',
            priceUSD: '14.62',
            logoURI: 'https://static.debank.com/image/avax_token/logo_url/avax/0b9c84359c84d6bdd5bfda9c2d4c4a82.png',
            coinKey: 'AVAX',
        },
    },
    {
        key: 'arb',
        chainType: 'EVM',
        name: 'Arbitrum',
        symbol: 'ETH',
        id: 42161,
        mainnet: true,
        logoURI: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/arbitrum.svg',
        tokenlistUrl: 'https://raw.githubusercontent.com/sushiswap/default-token-list/master/tokens/arbitrum.json',
        faucetUrls: ['https://bridge.arbitrum.io/'],
        multicallAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
        metamask: {
            chainId: '0xa4b1',
            blockExplorerUrls: ['https://arbiscan.io/'],
            chainName: 'Arbitrum',
            nativeCurrency: {
                name: 'AETH',
                symbol: 'AETH',
                decimals: 18,
            },
            rpcUrls: ['https://arb1.arbitrum.io/rpc'],
        },
        nativeToken: {
            address: '0x0000000000000000000000000000000000000000',
            chainId: 42161,
            symbol: 'ETH',
            decimals: 18,
            name: 'ETH',
            priceUSD: '1931.14',
            logoURI: 'https://static.debank.com/image/arb_token/logo_url/arb/d61441782d4a08a7479d54aea211679e.png',
            coinKey: 'ETH',
        },
    },
    {
        key: 'opt',
        chainType: 'EVM',
        name: 'Optimism',
        symbol: 'ETH',
        id: 10,
        mainnet: true,
        logoURI: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/optimism.svg',
        tokenlistUrl: 'https://static.optimism.io/optimism.tokenlist.json',
        faucetUrls: ['https://gateway.optimism.io/'],
        multicallAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
        metamask: {
            chainId: '0xa',
            blockExplorerUrls: ['https://optimistic.etherscan.io/'],
            chainName: 'Optimism',
            nativeCurrency: {
                name: 'ETH',
                symbol: 'ETH',
                decimals: 18,
            },
            rpcUrls: ['https://mainnet.optimism.io/'],
        },
        nativeToken: {
            address: '0x0000000000000000000000000000000000000000',
            chainId: 10,
            symbol: 'ETH',
            decimals: 18,
            name: 'ETH',
            priceUSD: '1931.14',
            logoURI: 'https://static.debank.com/image/op_token/logo_url/op/d61441782d4a08a7479d54aea211679e.png',
            coinKey: 'ETH',
        },
    },
    {
        key: 'mor',
        chainType: 'EVM',
        name: 'Moonriver',
        symbol: 'MOVR',
        id: 1285,
        mainnet: true,
        logoURI: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/moonriver.svg',
        tokenlistUrl: 'https://raw.githubusercontent.com/sushiswap/default-token-list/master/tokens/moonriver.json',
        multicallAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
        metamask: {
            chainId: '0x505',
            blockExplorerUrls: ['https://blockscout.moonriver.moonbeam.network/'],
            chainName: 'Moonriver',
            nativeCurrency: {
                name: 'Moonriver',
                symbol: 'MOVR',
                decimals: 18,
            },
            rpcUrls: ['https://rpc.api.moonriver.moonbeam.network'],
        },
        nativeToken: {
            address: '0x0000000000000000000000000000000000000000',
            chainId: 1285,
            symbol: 'MOVR',
            decimals: 18,
            name: 'MOVR',
            priceUSD: '5.22',
            logoURI:
                'https://static.debank.com/image/mtr_token/logo_url/0xb158870beb809ad955bf56065c5c10d7fd957cc0/aa42368ae1d5856d15c13ecc0ff74af6.png',
            coinKey: 'MOVR',
        },
    },
    {
        key: 'moo',
        chainType: 'EVM',
        name: 'Moonbeam',
        symbol: 'GLMR',
        id: 1284,
        mainnet: true,
        logoURI: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/moonbeam.svg',
        tokenlistUrl: 'https://raw.githubusercontent.com/BeamSwap/beamswap-tokenlist/main/tokenlist.json',
        multicallAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
        metamask: {
            chainId: '0x504',
            blockExplorerUrls: ['https://blockscout.moonbeam.network/'],
            chainName: 'Moonbeam',
            nativeCurrency: {
                name: 'GLMR',
                symbol: 'GLMR',
                decimals: 18,
            },
            rpcUrls: ['https://rpc.api.moonbeam.network'],
        },
        nativeToken: {
            address: '0x0000000000000000000000000000000000000000',
            chainId: 1284,
            symbol: 'GLMR',
            decimals: 18,
            name: 'GLMR',
            priceUSD: '0.2404',
            logoURI: 'https://static.debank.com/image/mobm_token/logo_url/mobm/a8442077d76b258297181c3e6eb8c9cc.png',
            coinKey: 'GLMR',
        },
    },
    {
        key: 'cel',
        chainType: 'EVM',
        name: 'CELO',
        symbol: 'CELO',
        id: 42220,
        mainnet: true,
        logoURI: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/celo.svg',
        tokenlistUrl: 'https://raw.githubusercontent.com/sushiswap/default-token-list/master/tokens/celo.json',
        faucetUrls: ['https://stakely.io/faucet/celo-platform', 'https://free-online-app.com/faucet-for-eth-evm-chains/'],
        multicallAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
        metamask: {
            chainId: '0xa4ec',
            blockExplorerUrls: ['https://explorer.celo.org/'],
            chainName: 'Celo Mainnet',
            nativeCurrency: {
                name: 'CELO',
                symbol: 'CELO',
                decimals: 18,
            },
            rpcUrls: ['https://forno.celo.org'],
        },
        nativeToken: {
            address: '0x471ece3750da237f93b8e339c536989b8978a438',
            chainId: 42220,
            symbol: 'CELO',
            decimals: 18,
            name: 'CELO',
            priceUSD: '0.566',
            logoURI:
                'https://static.debank.com/image/celo_token/logo_url/0x471ece3750da237f93b8e339c536989b8978a438/d5d37c2a693d70240afb561beb7e6821.png',
            coinKey: 'CELO',
        },
    },
    {
        key: 'fus',
        chainType: 'EVM',
        name: 'FUSE',
        symbol: 'FUSE',
        id: 122,
        mainnet: true,
        logoURI: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/fuse.svg',
        tokenlistUrl: 'https://raw.githubusercontent.com/sushiswap/default-token-list/master/tokens/fuse.json',
        multicallAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
        metamask: {
            chainId: '0x7a',
            blockExplorerUrls: ['https://explorer.fuse.io/'],
            chainName: 'Fuse Mainnet',
            nativeCurrency: {
                name: 'FUSE',
                symbol: 'FUSE',
                decimals: 18,
            },
            rpcUrls: ['https://rpc.fuse.io'],
        },
        nativeToken: {
            address: '0x0000000000000000000000000000000000000000',
            chainId: 122,
            symbol: 'FUSE',
            decimals: 18,
            name: 'FUSE',
            priceUSD: '0.06075',
            logoURI: 'https://static.debank.com/image/fuse_token/logo_url/fuse/6342e1cc4646e22d1e91956fdee942eb.png',
            coinKey: 'FUSE',
        },
    },
    {
        key: 'cro',
        chainType: 'EVM',
        name: 'Cronos',
        symbol: 'CRO',
        id: 25,
        mainnet: true,
        logoURI: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/cronos.svg',
        tokenlistUrl:
            'https://raw.githubusercontent.com/cronaswap/cronaswap-tokenlists/main/cronaswap-default.tokenlist.json',
        multicallAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
        metamask: {
            chainId: '0x19',
            blockExplorerUrls: ['https://cronos.crypto.org/explorer/'],
            chainName: 'Cronos',
            nativeCurrency: {
                name: 'Crypto.org Coin',
                symbol: 'CRO',
                decimals: 18,
            },
            rpcUrls: ['https://evm-cronos.crypto.org'],
        },
        nativeToken: {
            address: '0x0000000000000000000000000000000000000000',
            chainId: 25,
            symbol: 'CRO',
            decimals: 18,
            name: 'CRO',
            priceUSD: '0.06019',
            logoURI: 'https://static.debank.com/image/cro_token/logo_url/cro/affddd53019ffb9dbad0c724e12500c0.png',
            coinKey: 'CRO',
        },
    },
    {
        key: 'bob',
        chainType: 'EVM',
        name: 'Boba',
        symbol: 'ETH',
        id: 288,
        mainnet: true,
        logoURI: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/boba.png',
        tokenlistUrl:
            'https://raw.githubusercontent.com/OolongSwap/boba-community-token-list/main/build/boba.tokenlist.json',
        multicallAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
        metamask: {
            chainId: '0x120',
            blockExplorerUrls: ['https://blockexplorer.boba.network/'],
            chainName: 'Boba',
            nativeCurrency: {
                name: 'ETH',
                symbol: 'ETH',
                decimals: 18,
            },
            rpcUrls: ['https://mainnet.boba.network/'],
        },
        nativeToken: {
            address: '0x0000000000000000000000000000000000000000',
            chainId: 288,
            symbol: 'ETH',
            decimals: 18,
            name: 'ETH',
            priceUSD: '1931.14',
            logoURI: 'https://static.debank.com/image/boba_token/logo_url/boba/b1947b38a90e559eb950453965714be4.png',
            coinKey: 'ETH',
        },
    },
    {
        key: 'vel',
        chainType: 'EVM',
        name: 'Velas',
        symbol: 'VLX',
        id: 106,
        mainnet: true,
        multicallAddress: '0x6ede559F2Bd951777470595761672091CCD21Ac6',
        logoURI: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/velas.png',
        faucetUrls: ['https://stakely.io/faucet/velas-vlx'],
        metamask: {
            chainId: '0x6a',
            blockExplorerUrls: ['https://evmexplorer.velas.com/'],
            chainName: 'Velas',
            nativeCurrency: {
                name: 'VLX',
                symbol: 'VLX',
                decimals: 18,
            },
            rpcUrls: ['https://evmexplorer.velas.com/rpc'],
        },
        nativeToken: {
            address: '0x0000000000000000000000000000000000000000',
            symbol: 'VLX',
            decimals: 18,
            chainId: 106,
            name: 'Velas',
            coinKey: 'VLX',
            logoURI: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/tokens/vlx.png',
            priceUSD: '0',
        },
    },
    {
        key: 'aur',
        chainType: 'EVM',
        name: 'Aurora',
        symbol: 'ETH',
        id: 1313161554,
        mainnet: true,
        logoURI: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/aurora.png',
        tokenlistUrl: 'https://aurora.dev/tokens.json',
        multicallAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
        metamask: {
            chainId: '0x4e454152',
            blockExplorerUrls: ['https://aurorascan.dev/'],
            chainName: 'Aurora',
            nativeCurrency: {
                name: 'ETH',
                symbol: 'ETH',
                decimals: 18,
            },
            rpcUrls: ['https://mainnet.aurora.dev'],
        },
        nativeToken: {
            address: '0x0000000000000000000000000000000000000000',
            chainId: 1313161554,
            symbol: 'AETH',
            decimals: 18,
            name: 'AETH',
            priceUSD: '1931.14',
            logoURI: 'https://static.debank.com/image/aurora_token/logo_url/aurora/d61441782d4a08a7479d54aea211679e.png',
            coinKey: 'ETH',
        },
    },
]
