const route = {
  requestId: 'cd6a85f5-fca3-4703-b622-79ac8ed8e753',
  resultType: 'OK',
  route: {
    outputAmount: '331059811111897',
    outputAmountMin: '326118702048575',
    outputAmountUsd: 0.5495996838794431,
    swapper: {
      id: 'Stargate Aggregator',
      title: 'Stargate',
      logo: 'https://api.rango.exchange/swappers/stargate.svg',
      swapperGroup: 'Stargate',
      types: ['AGGREGATOR'],
      enabled: true,
    },
    from: {
      blockchain: 'POLYGON',
      symbol: 'MATIC',
      name: null,
      isPopular: false,
      chainId: '137',
      address: null,
      decimals: 18,
      image: 'https://api.rango.exchange/i/cFz5tK',
      blockchainImage: 'https://api.rango.exchange/blockchains/polygon.svg',
      usdPrice: 0.5542790405012632,
      supportedSwappers: [],
    },
    to: {
      blockchain: 'ARBITRUM',
      symbol: 'ETH',
      name: null,
      isPopular: false,
      chainId: '42161',
      address: null,
      decimals: 18,
      image: 'https://api.rango.exchange/i/nKxZFX',
      blockchainImage: 'https://api.rango.exchange/blockchains/arbitrum.svg',
      usdPrice: 1660.1220245778502,
      supportedSwappers: [],
    },
    fee: [
      {
        token: {
          blockchain: 'POLYGON',
          symbol: 'MATIC',
          name: null,
          isPopular: true,
          chainId: '137',
          address: null,
          decimals: 18,
          image: 'https://api.rango.exchange/i/cFz5tK',
          blockchainImage: 'https://api.rango.exchange/blockchains/polygon.svg',
          usdPrice: 0.5542790405012632,
          supportedSwappers: [
            'Wormhole',
            'ParaSwap Polygon',
            'Hyphen',
            'Satellite',
            'QuickSwap',
            'Voyager',
            'OneInchPolygon',
            'cBridge v2.0',
          ],
        },
        expenseType: 'FROM_SOURCE_WALLET',
        amount: '114901942899114644',
        name: 'Network Fee',
      },
      {
        token: {
          blockchain: 'POLYGON',
          symbol: 'MATIC',
          name: null,
          isPopular: true,
          chainId: '137',
          address: null,
          decimals: 18,
          image: 'https://api.rango.exchange/i/cFz5tK',
          blockchainImage: 'https://api.rango.exchange/blockchains/polygon.svg',
          usdPrice: 0.5542790405012632,
          supportedSwappers: [
            'Wormhole',
            'ParaSwap Polygon',
            'Hyphen',
            'Satellite',
            'QuickSwap',
            'Voyager',
            'OneInchPolygon',
            'cBridge v2.0',
          ],
        },
        expenseType: 'FROM_SOURCE_WALLET',
        amount: '2063914461587054727',
        name: 'Swapper Fee',
      },
      {
        token: {
          blockchain: 'POLYGON',
          symbol: 'MATIC',
          name: null,
          isPopular: true,
          chainId: '137',
          address: null,
          decimals: 18,
          image: 'https://api.rango.exchange/i/cFz5tK',
          blockchainImage: 'https://api.rango.exchange/blockchains/polygon.svg',
          usdPrice: 0.5542790405012632,
          supportedSwappers: [
            'Wormhole',
            'ParaSwap Polygon',
            'Hyphen',
            'Satellite',
            'QuickSwap',
            'Voyager',
            'OneInchPolygon',
            'cBridge v2.0',
          ],
        },
        expenseType: 'FROM_SOURCE_WALLET',
        amount: '645215785110828426',
        name: 'Swapper Fee',
      },
    ],
    feeUsd: 1.5653018523945053,
    amountRestriction: null,
    estimatedTimeInSeconds: 120,
    path: [
      {
        swapper: {
          id: 'QuickSwap',
          title: 'QuickSwap',
          logo: 'https://api.rango.exchange/swappers/quick-swap.png',
          swapperGroup: 'Quick Swap',
          types: ['DEX'],
          enabled: true,
        },
        swapperType: 'DEX',
        from: {
          blockchain: 'POLYGON',
          symbol: 'MATIC',
          name: null,
          isPopular: false,
          chainId: '137',
          address: null,
          decimals: 18,
          image: 'https://api.rango.exchange/i/cFz5tK',
          blockchainImage: 'https://api.rango.exchange/blockchains/polygon.svg',
          usdPrice: 0.5542790405012632,
          supportedSwappers: [],
        },
        to: {
          blockchain: 'POLYGON',
          symbol: 'USDT',
          name: null,
          isPopular: false,
          chainId: '137',
          address: '0xc2132d05d31c914a87c6611c10748aeb04b58e8f',
          decimals: 6,
          image:
            'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png',
          blockchainImage: 'https://api.rango.exchange/blockchains/polygon.svg',
          usdPrice: 1.002,
          supportedSwappers: [],
        },
        inputAmount: '999499999999999999',
        expectedOutput: '552981',
        estimatedTimeInSeconds: 30,
      },
      {
        swapper: {
          id: 'stargate',
          title: 'Stargate',
          logo: 'https://api.rango.exchange/swappers/stargate.svg',
          swapperGroup: 'Stargate',
          types: ['BRIDGE'],
          enabled: true,
        },
        swapperType: 'BRIDGE',
        from: {
          blockchain: 'POLYGON',
          symbol: 'USDT',
          name: null,
          isPopular: false,
          chainId: '137',
          address: '0xc2132d05d31c914a87c6611c10748aeb04b58e8f',
          decimals: 6,
          image: 'https://api.rango.exchange/tokens/ETH/USDT.png',
          blockchainImage: 'https://api.rango.exchange/blockchains/polygon.svg',
          usdPrice: 1.002,
          supportedSwappers: [],
        },
        to: {
          blockchain: 'ARBITRUM',
          symbol: 'USDT',
          name: null,
          isPopular: false,
          chainId: '42161',
          address: '0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9',
          decimals: 6,
          image: 'https://api.rango.exchange/tokens/ETH/USDT.png',
          blockchainImage: 'https://api.rango.exchange/blockchains/arbitrum.svg',
          usdPrice: 1.002,
          supportedSwappers: [],
        },
        inputAmount: '552981',
        expectedOutput: '552650',
        estimatedTimeInSeconds: 120,
      },
      {
        swapper: {
          id: 'SushiArbitrum',
          title: 'SushiSwap',
          logo: 'https://api.rango.exchange/swappers/sushi.png',
          swapperGroup: 'Sushi Swap',
          types: ['DEX'],
          enabled: true,
        },
        swapperType: 'DEX',
        from: {
          blockchain: 'ARBITRUM',
          symbol: 'USDT',
          name: null,
          isPopular: false,
          chainId: '42161',
          address: '0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9',
          decimals: 6,
          image: 'https://assets.coingecko.com/coins/images/325/thumb/Tether-logo.png?1598003707',
          blockchainImage: 'https://api.rango.exchange/blockchains/arbitrum.svg',
          usdPrice: 1.002,
          supportedSwappers: [],
        },
        to: {
          blockchain: 'ARBITRUM',
          symbol: 'ETH',
          name: null,
          isPopular: false,
          chainId: '42161',
          address: null,
          decimals: 18,
          image: 'https://api.rango.exchange/i/nKxZFX',
          blockchainImage: 'https://api.rango.exchange/blockchains/arbitrum.svg',
          usdPrice: 1660.1220245778502,
          supportedSwappers: [],
        },
        inputAmount: '552650',
        expectedOutput: '331059811111897',
        estimatedTimeInSeconds: 30,
      },
    ],
  },
  error: null,
}
