const quote = {
  requestId: 'ae335f71-5ade-4837-97df-80e50c8c5fec',
  resultType: 'OK',
  route: {
    outputAmount: '2995800734298293743033',
    outputAmountMin: '2965917621973668394390',
    outputAmountUsd: 1654.5508468480443,
    swapper: {
      id: 'Hyphen Aggregator',
      title: 'Hyphen',
      logo: 'https://api.rango.exchange/swappers/hyphen.svg',
      swapperGroup: 'Hyphen',
      types: ['AGGREGATOR'],
      enabled: true,
    },
    from: {
      blockchain: 'ETH',
      symbol: 'ETH',
      name: null,
      isPopular: false,
      chainId: '1',
      address: null,
      decimals: 18,
      image: 'https://api.rango.exchange/tokens/ETH/ETH.png',
      blockchainImage: 'https://api.rango.exchange/blockchains/ethereum.svg',
      usdPrice: 1658.8240418795547,
      supportedSwappers: [],
    },
    to: {
      blockchain: 'POLYGON',
      symbol: 'MATIC',
      name: null,
      isPopular: false,
      chainId: '137',
      address: null,
      decimals: 18,
      image: 'https://api.rango.exchange/i/cFz5tK',
      blockchainImage: 'https://api.rango.exchange/blockchains/polygon.svg',
      usdPrice: 0.5522900197951883,
      supportedSwappers: [],
    },
    fee: [
      {
        token: {
          blockchain: 'ETH',
          symbol: 'ETH',
          name: null,
          isPopular: true,
          chainId: '1',
          address: null,
          decimals: 18,
          image: 'https://api.rango.exchange/tokens/ETH/ETH.png',
          blockchainImage: 'https://api.rango.exchange/blockchains/ethereum.svg',
          usdPrice: 1658.8240418795547,
          supportedSwappers: [
            'Wormhole',
            'ThorChain',
            'Arbitrum Bridge',
            'Hyphen',
            'Synapse Bridge',
            'Satellite',
            'MayaProtocol',
            'Voyager',
            'stargate',
            'cBridge v2.0',
            'Optimism Bridge',
            'Across',
            'Lido',
            'Polygon Bridge',
            'OneInchEth',
            'XY Finance',
            'Rainbow Bridge',
            'ParaSwap Eth',
            'EthUniSwapV2',
            'Orbiter',
          ],
        },
        expenseType: 'FROM_SOURCE_WALLET',
        amount: '17576236233980921',
        name: 'Network Fee',
      },
    ],
    feeUsd: 29.15588323068211,
    amountRestriction: {
      min: '3436899897666193',
      max: '9431397824693236162',
      type: 'EXCLUSIVE',
    },
    estimatedTimeInSeconds: 90,
    path: [
      {
        swapper: {
          id: 'OneInchEth',
          title: '1Inch',
          logo: 'https://api.rango.exchange/swappers/1inch.svg',
          swapperGroup: '1Inch',
          types: ['DEX'],
          enabled: true,
        },
        swapperType: 'DEX',
        from: {
          blockchain: 'ETH',
          symbol: 'ETH',
          name: null,
          isPopular: false,
          chainId: '1',
          address: null,
          decimals: 18,
          image: 'https://api.rango.exchange/tokens/ETH/ETH.png',
          blockchainImage: 'https://api.rango.exchange/blockchains/ethereum.svg',
          usdPrice: 1658.8240418795547,
          supportedSwappers: [],
        },
        to: {
          blockchain: 'ETH',
          symbol: 'MATIC',
          name: null,
          isPopular: false,
          chainId: '1',
          address: '0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0',
          decimals: 18,
          image: 'https://tokens.1inch.io/0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0.png',
          blockchainImage: 'https://api.rango.exchange/blockchains/ethereum.svg',
          usdPrice: 0.551843,
          supportedSwappers: [],
        },
        inputAmount: '999499999999999999',
        expectedOutput: '2995388375143150636258',
        estimatedTimeInSeconds: 600,
      },
      {
        swapper: {
          id: 'Hyphen',
          title: 'Hyphen',
          logo: 'https://api.rango.exchange/swappers/hyphen.svg',
          swapperGroup: 'Hyphen',
          types: ['BRIDGE'],
          enabled: true,
        },
        swapperType: 'BRIDGE',
        from: {
          blockchain: 'ETH',
          symbol: 'MATIC',
          name: null,
          isPopular: false,
          chainId: '1',
          address: '0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0',
          decimals: 18,
          image: 'https://biconomy-public-assets.s3.amazonaws.com/tokens/matic-icon.svg',
          blockchainImage: 'https://api.rango.exchange/blockchains/ethereum.svg',
          usdPrice: 0.551843,
          supportedSwappers: [],
        },
        to: {
          blockchain: 'POLYGON',
          symbol: 'MATIC',
          name: null,
          isPopular: false,
          chainId: '137',
          address: null,
          decimals: 18,
          image: 'https://api.rango.exchange/i/cFz5tK',
          blockchainImage: 'https://api.rango.exchange/blockchains/polygon.svg',
          usdPrice: 0.5522900197951883,
          supportedSwappers: [],
        },
        inputAmount: '2995388375143150636258',
        expectedOutput: '2995800734298293743033',
        estimatedTimeInSeconds: 60,
      },
    ],
  },
  error: null,
}
