/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "container": string|undefined
  "iconContainer": string|undefined
  "symbolNameContainer": string|undefined
}
