/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export interface CssIdentifiersMap {
	beacon: string | undefined
	container: string | undefined
	green: string | undefined
	primary: string | undefined
	red: string | undefined
}
