/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "active": string|undefined
  "comingSoon": string|undefined
  "header": string|undefined
  "logoContainer": string|undefined
  "navigatorContainer": string|undefined
}
