/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export interface CssIdentifiersMap {
	root: string | undefined
}
declare module '*.pcss' {
	const content: Record<string, string>
	export default content
}
