/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export interface CssIdentifiersMap {
	id: string | undefined
	infoContainer: string | undefined
	line: string | undefined
	modalPopoverContainer: string | undefined
	tableContainer: string | undefined
}
