#!/usr/bin/env sh
set -euo pipefail

# Branch name validation
./$(dirname "$0")/validateBranchName.sh "$(git rev-parse --abbrev-ref HEAD)"

# Pre-commit checks
npm run format
npm run lint:fix
git add -A .

echo "✅ Pre-commit checks passed successfully."
exit 0