/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export interface CssIdentifiersMap {
	chartContainer: string | undefined
	container: string | undefined
}
