/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "active": string|undefined
  "container": string|undefined
  "logOutButton": string|undefined
  "menu": string|undefined
  "menuActive": string|undefined
  "menuBtn": string|undefined
  "menuIcon": string|undefined
  "navIcon": string|undefined
  "secondary": string|undefined
}
