/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "cardHeader": string|undefined
  "container": string|undefined
  "mainCardStack": string|undefined
  "secondaryCardStack": string|undefined
}
