/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "container": string|undefined
  "green": string|undefined
  "grey": string|undefined
  "lg": string|undefined
  "main": string|undefined
  "mainDarker": string|undefined
  "md": string|undefined
  "red": string|undefined
  "tag": string|undefined
  "xs": string|undefined
}
