/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  container: string | undefined
  lg: string | undefined
  md: string | undefined
  tag: string | undefined
  xs: string | undefined
}
